services:
  db:
    image: postgres:15
    container_name: todo_postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}    # Read from .env
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Read from .env
      POSTGRES_DB: ${POSTGRES_DB}  # Read from .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: todo_fastapi
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  postgres_data:
